version: '3.1'
services:
  api:
    build: .
    ports:
     - "8080:8080"

    environment:
        DATABASE_HOST: db
        DATABASE_USER: root
        DATABASE_PASSWORD: axdvfcsz
        DATABASE_NAME: namshi
        DATABASE_TEST_NAME: namshi_test
        PORT: 8080

  db:
    image: mysql:5.7.22
    ports:
      - "3306:3306"
    expose:
     - 3306
    environment:
        MYSQL_ROOT_PASSWORD: axdvfcsz
        MYSQL_DATABASE: namshi